[package]
name = "netwatch-tui"
version = "0.3.3"
edition = "2021"
authors = ["Matt Hartley <matthew.t.hartley@gmail.com>"]
description = "Real-time network diagnostics in your terminal â€” like htop for your network"
license = "MIT"
repository = "https://github.com/matthart1983/netwatch"
homepage = "https://github.com/matthart1983/netwatch"
readme = "README.md"
keywords = ["network", "tui", "terminal", "packet-capture", "diagnostics"]
categories = ["command-line-utilities", "network-programming"]
exclude = ["demo.gif", "demo.tape", ".DS_Store"]

[lib]
name = "netwatch"
path = "src/lib.rs"

[[bin]]
name = "netwatch"
path = "src/main.rs"

[dependencies]
ratatui = "0.27"
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
chrono = "0.4"
pcap = "2"
ureq = "2"
serde_json = "1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["net", "ioctl", "hostname"] }
